language: minimal

addons:
    apt:
        packages:
            - docker-ce

services:
  - docker

script:
  - docker build -t "$DOCKER_USERNAME/unbound_exporter:latest" .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME/unbound_exporter:latest"
