name: Docker Image CI

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "37 0 * * 1"
  push:
    branches:
      - main
      - master

env:
  DOCKER_BUILDKIT: 1

jobs:
  build_unbound_exporter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Create folder for images
        run: |
          sudo mkdir -p /images
          sudo chmod 777 /images

      - name: Build image
        run: docker build -t horaynarea/unbound_exporter:latest .

      - name: Save image
        run: docker save horaynarea/unbound_exporter -o /images/unbound_exporter.tar.gz

      - name: Cache image
        uses: actions/cache@v3
        with:
          path: /images/unbound_exporter.tar.gz
          key: ${{ github.run_id }}-${{ github.run_number }}-unbound_exporter

  push_images:
    needs: build_unbound_exporter
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Create folder for images
        run: |
          sudo mkdir -p /images
          sudo chmod 777 /images

      - name: Load unbound_exporter cache
        uses: actions/cache@v3
        with:
          path: /images/unbound_exporter.tar.gz
          key: ${{ github.run_id }}-${{ github.run_number }}-unbound_exporter

      - name: Load docker images
        run: |
          docker load -i /images/unbound_exporter.tar.gz

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images
        run: docker push horaynarea/unbound_exporter:latest
